version: "3"

services:
  discord-musicbot:
    build: .
    image: discord-musicbot:latest
    container_name: discord-musicbot
    restart: unless-stopped
    networks:
      - lavalink-net
    ports:
      - "80:80"
    depends_on:
      - lavalink
    volumes:
      - ./botconfig.js:/usr/src/app/botconfig.js:ro

  lavalink:
    image: fredboat/lavalink:dev-
    container_name: music-lavalink
    hostname: lavalink
    restart: unless-stopped
    networks:
      - lavalink-net
    ports:
      - "127.0.0.1:1304:1304"
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro
      - ./logs:/opt/Lavalink/logs

networks:
  lavalink-net:
